local:
  service: Disk
  root: <%= Rails.root.join("storage/images") %>
google:
  service: GCS
  credentials: '/home/deployer/ctcm/shared/CTCM-12d6b8857450.json'
  project: 'ctcm-207213'
  bucket: 'ctcm_storage'
